import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/Footer";


const poppins = Poppins({
  variable: "--font-poppins",  
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Omnibooks Digital Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${poppins.variable} h-full antialiased`}    >
      <body className={`#{poppins.className} min-h-full flex flex-col`}>
        <Navbar />       
        <main className="container mx-auto">{children}</main>
        <Footer />
        </body>
    </html>
  );
}
